apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpu-device-plugin
  namespace: intel-device-plugins-system
spec:
  nodeSelector:
    feature.node.kubernetes.io/pci-0300_8086.present: "true"
  image: intel/intel-gpu-plugin:0.30.0
  logLevel: 4