apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
data:
  config.yml: |
    mqtt:
      enabled: false

    ffmpeg:
      hwaccel_args: preset-vaapi
      
    go2rtc:
      streams:
        dummy: ffmpeg:rtsp://127.0.0.1:554/null#video=copy

    detectors:
      coral:
        type: cpu
        num_threads: 3

    cameras:
      dummy_cam:
        enabled: false
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:554/null
              roles:
                - detect

    record:
      enabled: true
      retain:
        days: 7
        mode: all

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14

    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.7

    ui:
      timezone: America/New_York
      time_format: 12hour
      date_style: short
      time_style: medium
      strftime_fmt: "%m/%d/%Y %I:%M %p"

    telemetry:
      version_check: true