apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
data:
  config.yml: |
    mqtt:
      enabled: false

    ffmpeg:
      hwaccel_args: preset-vaapi
      
    go2rtc:
      streams:
        # Add your camera streams here
        # example_cam:
        #   - rtsp://user:pass@192.168.1.100:554/stream1

    detectors:
      coral:
        type: cpu
        num_threads: 3

    cameras:
      # Example camera - uncomment and modify
      # front_door:
      #   ffmpeg:
      #     inputs:
      #       - path: rtsp://user:pass@192.168.1.100:554/stream1
      #         roles:
      #           - detect
      #       - path: rtsp://user:pass@192.168.1.100:554/stream2
      #         roles:
      #           - record
      #   detect:
      #     width: 1920
      #     height: 1080
      #     fps: 5
      #   record:
      #     enabled: true
      #     retain:
      #       days: 7
      #       mode: motion
      #     events:
      #       retain:
      #         default: 14
      #         mode: active_objects

    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: motion

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14

    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.7

    ui:
      live_mode: mse
      timezone: America/New_York
      use_experimental: false
      time_format: 12hour
      date_style: short
      time_style: medium
      strftime_fmt: "%m/%d/%Y %I:%M %p"

    telemetry:
      version_check: true