apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      nodeSelector:
        feature.node.kubernetes.io/pci-0300_8086.present: "true"
      initContainers:
      # Add an init container to copy the config file
      - name: config-init
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            # Copy the config from ConfigMap to the persistent volume
            cp /tmp/config/config.yml /config/config.yml
            # Ensure proper permissions
            chmod 644 /config/config.yml
        volumeMounts:
        - name: frigate-config
          mountPath: /tmp/config
        - name: config
          mountPath: /config
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8554
          name: rtsp
        - containerPort: 8555
          name: webrtc-tcp
          protocol: TCP
        - containerPort: 8555
          name: webrtc-udp
          protocol: UDP
        env:
        - name: FRIGATE_RTSP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: frigate-secrets
              key: rtsp-password
        - name: TZ
          value: "America/New_York"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media/frigate
        - name: models
          mountPath: /models
          readOnly: true
        # Remove the conflicting ConfigMap mount
        # - name: frigate-config
        #   mountPath: /config/config.yml
        #   subPath: config.yml
        #   readOnly: true
        - name: dri
          mountPath: /dev/dri
        - name: shm
          mountPath: /dev/shm
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            gpu.intel.com/i915: "1"
          limits:
            memory: "4Gi"
            cpu: "2000m"
            gpu.intel.com/i915: "1"
        securityContext:
          privileged: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: frigate-config
      - name: media
        nfs:
          server: 10.2.10.100
          path: /mnt/NAS-WIL/Media/frigate
          readOnly: false
      - name: models
        nfs:
          server: 10.2.10.100
          path: /mnt/NAS-WIL/Media/frigate/models
          readOnly: true
      - name: frigate-config
        configMap:
          name: frigate-config
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 10Gi