romm_db_root_password: ENC[AES256_GCM,data:3YMNbHbeh72V8Yj01tUhj/J72SN46w==,iv:9vT3P52p6jjAG/5wyV1faHJFe/PykCY04S0MRGd7zI0=,tag:eTV90zpcyjqgfIM3JVT25A==,type:str]
romm_db_password: ENC[AES256_GCM,data:l6iIePgkfVWZokheJZC2s6/gEWsGKA==,iv:SHCignEGcPI4gPArk2B+8Mg9rOzPj/PrJuAC1XVT7Wo=,tag:122LUX1hL/vcLeivMRKz0w==,type:str]
romm_auth_secret: ENC[AES256_GCM,data:jO60PpHNzR8WmTziehBu2W8e+SCJROQwGMXzoAWFeK1POKTqdv7xHQxp/Q==,iv:5GLtNfuVXLL8XWfSiJ/T44E/+iWVEZQLnsv3qZGqatM=,tag:uuphyuAmZ9hC1ggCCnmiHA==,type:str]
romm_igdb_client_id: ENC[AES256_GCM,data:NPKplM84mmRyugtRB4k4pgoioSWuKnMTXSeIPRkE,iv:QisHTiLx4T8jWIdTfFmdV+swB0eWZaiqUTgI92LFZYU=,tag:aHzVI9l1ysOayBvoDZMEcg==,type:str]
romm_igdb_client_secret: ENC[AES256_GCM,data:6kfuIBzWgFBGk5TJA1WLUltAO2RZoFibk9YcaR6P,iv:tCKukJXUS8InM4Wwz5hnM7FKLumSfT+Mv/U/yzMGiEU=,tag:FeolvBWScuvhwvBv5Fx8UA==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbmRBNlJvSnVObnlHbUwz
            UERCRyswZStrcHJld2s0WjUzRURxTEx1eldVCjdCcGg3NHJ3V3B5NWkyeVR3dlVC
            T3k5d3ZDaVNDcnhTZFdUcXRTcUhNaXMKLS0tIGsyK2M0Z3pZS3p2dEJZMys5bGVQ
            WHNnN3VyRkpSVVk3bWg1RXJJNjdSb3MKV4nJXwyxUGy6pRvY7l1NahuZZMmI/oQF
            gUpZ7kDM9DKH0VtDk/zGtVa/dNan3K+4YveYfCcmoAeonwaeCQq0uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T11:39:43Z"
    mac: ENC[AES256_GCM,data:60tgOBWYVTB/Hp4rz1ayrdE/vt+DZhEf6EzCs8K0hdojchJCgFCCg6JD/woTpM56EdjICMF6vfiBKKZ8PZ/hF7P8zq8tAm3TXULEJeugKjfU6PVhxy6CHn9u5ftUT+toPjpshDuiZVtGnkxGe5OAom5dcZIN+ByOgoO6aiDQ65A=,iv:7rvdjMwEN7i/dB8/RbjwJXMDQHrj+qEBKCzyU/JrIow=,tag:Zc//EJhiPaVR4hrNEA45zw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
