services:
  tui:
    build:
      context: .
    image: homelab-tui
    stdin_open: true
    tty: true
    volumes:
      - ..:/homelab
      - /homelab/tui/.venv
      - ~/.ssh:/root/.ssh:ro
    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: sync
          path: ./src
          target: /homelab/tui/src
