services:
  nzbget:
    container_name: sabnzbd
    environment:
      - PGID=1024
      - PUID=1024
      - UMASK=022
    image: linuxserver/sabnzbd
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /home/sfcal/sabnzbd:/config
      - /mnt/data/usenet:/data/usenet
  nzbhydra2:
    container_name: nzbhydra2
    environment:
      - PGID=1024
      - PUID=1024
      - UMASK=022
    image: linuxserver/nzbhydra2
    ports:
      - "5076:5076"
    restart: unless-stopped
    volumes:
      - /home/sfcal/hydra2:/config
  sonarr:
    container_name: sonarr
    depends_on:
      - nzbget
      - nzbhydra2
    environment:
      - PGID=1024
      - PUID=1024
      - UMASK=022
    image: linuxserver/sonarr
    links:
      - nzbget
    ports:
      - "8989:8989"
    restart: unless-stopped
    volumes:
      - /home/sfcal/sonarr:/config
      - /mnt/data:/data
  radarr:
    container_name: radarr
    depends_on:
      - nzbget
      - nzbhydra2
    environment:
      - PGID=1024
      - PUID=1024
      - UMASK=022
    image: linuxserver/radarr
    links:
      - nzbget
    ports:
      - "7878:7878"
    restart: unless-stopped
    volumes:
      - /home/sfcal/radarr:/config
      - /mnt/data:/data
  plex:
    container_name: plex
    environment:
      - PGID=1024
      - PUID=1024
      - UMASK=022
        #- PLEX_CLAIM=
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    image: linuxserver/plex
    ports:
      - 32401:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped
    volumes:

      - /home/sfcal/plex:/config
      - /mnt/data/media:/data/media
      - /mnt/data/transcode:/transcode
      - /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
      - /usr/lib/x86_64-linux-gnu/libnvidia-decode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-decode.so.1
      # Additional required NVIDIA libraries
      - /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1
      - /usr/lib/x86_64-linux-gnu/libnvidia-gl.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-gl.so.1
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  watchtower:
    container_name: watchtower
    environment:
      - BASE_URL=/
      - PGID=1024
      - PUID=1024
      - TZ=Etc/UTC
      - UMASK=022
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ombi:
    container_name: ombi
    environment:
      - BASE_URL=/
      - PGID=1024
      - PUID=1024
      - TZ=Etc/UTC
      - UMASK=022
    image: lscr.io/linuxserver/ombi:latest
    ports:
      - "3579:3579"
    restart: unless-stopped
    volumes:
      - /home/sfcal/ombi:/config
  tdarr:
    container_name: tdarr
    environment:
      - PGID=1024
      - PUID=1024
      - UMASK=022
      - TZ=Etc/UTC
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=InternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - "8265:8265"
      - "8266:8266"
    restart: unless-stopped
    volumes:
      - /home/sfcal/tdarr/server:/app/server
      - /home/sfcal/tdarr/configs:/app/configs
      - /home/sfcal/tdarr/logs:/app/logs
      - /mnt/data/:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

