networks:
  traefik-public:
    external: true

secrets:
  cf-token:
    file: ./cf-token

services:
  traefik:
    image: traefik:v3.5.4
    container_name: traefik
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 512m
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.sfc.al`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=https"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-dashboard.tls.domains[0].main=sfc.al"
      - "traefik.http.routers.traefik-dashboard.tls.domains[0].sans=*.sfc.al"
    networks:
      - traefik-public
    secrets:
      - cf-token
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=samuel.f.calvert@gmail.com
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf-token
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/sfcal/traefik/config/traefik.yaml:/traefik.yaml:ro
      - /home/sfcal/traefik/config/acme.json:/acme.json
      - /home/sfcal/traefik/config/config.yaml:/config.yaml:ro
      - /home/sfcal/traefik/logs:/var/log/traefik

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.5
    container_name: sabnzbd
    restart: unless-stopped
    mem_limit: 4g
    mem_reservation: 2g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.sfc.al`)"
      - "traefik.http.routers.sabnzbd.entrypoints=https"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.routers.sabnzbd.tls.certresolver=cloudflare"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
    networks:
      - traefik-public
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
    ports:
      - "8080:8080"
    volumes:
      - /home/sfcal/sabnzbd:/config
      - /mnt/data/usenet:/data/usenet

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.30.0
    container_name: prowlarr
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.sfc.al`)"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=cloudflare"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
      - traefik-public
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
    ports:
      - "9696:9696"
    volumes:
      - /home/sfcal/prowlarr:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.11
    container_name: sonarr
    restart: unless-stopped
    mem_limit: 4g
    mem_reservation: 2g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.sfc.al`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=cloudflare"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - traefik-public
    depends_on:
      - sabnzbd
      - prowlarr
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
    ports:
      - "8989:8989"
    volumes:
      - /home/sfcal/sonarr:/config
      - /mnt/data:/data

  radarr:
    image: lscr.io/linuxserver/radarr:5.16.4
    container_name: radarr
    restart: unless-stopped
    mem_limit: 4g
    mem_reservation: 2g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.radarr.rule=Host(`radarr.sfc.al`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - traefik-public
    depends_on:
      - sabnzbd
      - prowlarr
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
    ports:
      - "7878:7878"
    volumes:
      - /home/sfcal/radarr:/config
      - /mnt/data:/data

  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.3
    container_name: bazarr
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.sfc.al`)"
      - "traefik.http.routers.bazarr.entrypoints=https"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=cloudflare"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    networks:
      - traefik-public
    depends_on:
      - sonarr
      - radarr
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
      - TZ=Etc/UTC
    ports:
      - "6767:6767"
    volumes:
      - /home/sfcal/bazarr:/config
      - /mnt/data/media/movies:/movies
      - /mnt/data/media/tv:/tv

  plex:
    image: lscr.io/linuxserver/plex:1.42.2
    container_name: plex
    restart: unless-stopped
    mem_limit: 20g
    mem_reservation: 10g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.plex.rule=Host(`plex.sfc.al`)"
      - "traefik.http.routers.plex.entrypoints=https"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=cloudflare"
      - "traefik.http.routers.plex.middlewares=plex-headers@file"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.services.plex.loadbalancer.server.scheme=http"
    networks:
      - traefik-public
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
      - VERSION=docker
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - /home/sfcal/plex:/config
      - /mnt/data/media:/data/media
      - /dev/shm/plex:/transcode
    devices:
      - /dev/dri:/dev/dri

  tunarr:
    image: chrisbenincasa/tunarr:0.12.0
    container_name: tunarr
    restart: unless-stopped
    mem_limit: 6g
    mem_reservation: 3g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.tunarr.rule=Host(`tunarr.sfc.al`)"
      - "traefik.http.routers.tunarr.entrypoints=https"
      - "traefik.http.routers.tunarr.tls=true"
      - "traefik.http.routers.tunarr.tls.certresolver=cloudflare"
      - "traefik.http.services.tunarr.loadbalancer.server.port=8000"
    networks:
      - traefik-public
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
      - TZ=Etc/UTC
    ports:
      - "8000:8000"
    volumes:
      - /home/sfcal/tunarr:/config
      - /mnt/data/media:/media:ro
      - /dev/shm/tunarr:/cache
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - '993'

  pulsarr:
    image: lakker/pulsarr:3.2.13
    container_name: pulsarr
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.pulsarr.rule=Host(`pulsarr.sfc.al`)"
      - "traefik.http.routers.pulsarr.entrypoints=https"
      - "traefik.http.routers.pulsarr.tls=true"
      - "traefik.http.routers.pulsarr.tls.certresolver=cloudflare"
      - "traefik.http.services.pulsarr.loadbalancer.server.port=3003"
    networks:
      - traefik-public
    depends_on:
      - sonarr
      - radarr
      - plex
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
      - TZ=Etc/UTC
      - baseUrl=http://10.2.0.5
      - port=3003
      - logLevel=info
      - NODE_ARGS=--log-both
    ports:
      - "3003:3003"
    volumes:
      - /home/sfcal/pulsarr/data:/app/data
      - /home/sfcal/pulsarr/.env:/app/.env
  
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:0.9.2
    container_name: cleanuparr
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 512m
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.cleanuparr.rule=Host(`cleanuparr.sfc.al`)"
      - "traefik.http.routers.cleanuparr.entrypoints=https"
      - "traefik.http.routers.cleanuparr.tls=true"
      - "traefik.http.routers.cleanuparr.tls.certresolver=cloudflare"
      - "traefik.http.services.cleanuparr.loadbalancer.server.port=11011"
    networks:
      - traefik-public
    depends_on:
      - sonarr
      - radarr
      - sabnzbd
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
      - TZ=Etc/UTC
      - PORT=11011
    ports:
      - "11011:11011"
    volumes:
      - /home/sfcal/cleanuparr:/config

  huntarr:
    image: ghcr.io/plexguide/huntarr:v1.0.8
    container_name: huntarr
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 512m
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.huntarr.rule=Host(`huntarr.sfc.al`)"
      - "traefik.http.routers.huntarr.entrypoints=https"
      - "traefik.http.routers.huntarr.tls=true"
      - "traefik.http.routers.huntarr.tls.certresolver=cloudflare"
      - "traefik.http.services.huntarr.loadbalancer.server.port=9705"
    networks:
      - traefik-public
    depends_on:
      - sonarr
      - radarr
      - prowlarr
    environment:
      - TZ=Etc/UTC
    ports:
      - "9705:9705"
    volumes:
      - /home/sfcal/huntarr:/config

  tdarr-server:
    image: ghcr.io/haveagitgat/tdarr:2.27.04
    container_name: tdarr-server
    restart: unless-stopped
    mem_limit: 10g
    mem_reservation: 5g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.sfc.al`)"
      - "traefik.http.routers.tdarr.entrypoints=https"
      - "traefik.http.routers.tdarr.tls=true"
      - "traefik.http.routers.tdarr.tls.certresolver=cloudflare"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
    networks:
      - traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Etc/UTC
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=TdarrServer
    ports:
      - "8265:8265"
      - "8266:8266"
    volumes:
      - /home/sfcal/tdarr/server:/app/server
      - /home/sfcal/tdarr/configs:/app/configs
      - /home/sfcal/tdarr/logs:/app/logs
      - /home/sfcal/tdarr/data:/app/data
      - /mnt/data/media:/media
      - /dev/shm/tdarr:/temp
    devices:
      - /dev/dri:/dev/dri

#  tdarr-node:
#    image: ghcr.io/haveagitgat/tdarr_node:2.27.04
#    container_name: tdarr-node
#    restart: unless-stopped
#    mem_limit: 16g
#    mem_reservation: 8g
#    networks:
#      - traefik-public
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UMASK=022
#      - TZ=Etc/UTC
#      - nodeID=1
#      - nodeIP=0.0.0.0
#      - nodePort=8267
#      - serverIP=tdarr-server
#      - serverPort=8266
#      - inContainer=true
#      - internalnode=true
#      - ffmpegVersion=6
#      - nodeName=TdarrNode1
#    volumes:
#      - /home/sfcal/tdarr/configs:/app/configs
#      - /home/sfcal/tdarr/logs:/app/logs
#      - /mnt/data/media:/media
#      - /dev/shm/tdarr:/temp
#    devices:
#      - /dev/dri:/dev/dri

  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.2
    container_name: frigate
    restart: unless-stopped
    mem_limit: 4g
    mem_reservation: 2g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.frigate.rule=Host(`frigate.sfc.al`)"
      - "traefik.http.routers.frigate.entrypoints=https"
      - "traefik.http.routers.frigate.tls=true"
      - "traefik.http.routers.frigate.tls.certresolver=cloudflare"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
    networks:
      - traefik-public
    environment:
      - PGID=1000
      - PUID=1000
      - UMASK=022
      - TZ=America/New_York
      - FRIGATE_RTSP_PASSWORD=SuperSecure00  # Change this to a secure password
    ports:
      - "5000:5000"    # Web UI
      - "8554:8554"    # RTSP
      - "8555:8555/tcp" # WebRTC over TCP
      - "8555:8555/udp" # WebRTC over UDP
    volumes:
      - /home/sfcal/frigate:/config
      - /mnt/data/frigate:/media/frigate
      - /home/sfcal/frigate/models:/models:ro
      - /dev/shm/frigate:/dev/shm
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri  # Intel GPU for hardware acceleration
    privileged: true
    shm_size: 1g
