apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpu-device-plugin
  namespace: intel-device-plugins-system
spec:
  nodeSelector:
    kubernetes.io/hostname: k3s-worker-01
  image: intel/intel-gpu-plugin:0.30.0
  logLevel: 4