apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: snapshot-controller
      version: "3.0.6"
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: registry.k8s.io/sig-storage/snapshot-controller
      tag: "v8.0.1"
    args:
      - --v=2
      - --leader-election=false
    resources:
      limits:
        cpu: 500m
        memory: 300Mi
      requests:
        cpu: 10m
        memory: 20Mi