apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-api-key
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: radarr-api-key
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: radarr
      property: api-key