apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: prod
  CLUSTER_DOMAIN: home.local
  CLUSTER_REGION: homelab
  # Storage
  STORAGE_CLASS: ceph-rbd
  VOLSYNC_ENABLED: "true"
  VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool
  # Ceph Configuration
  CEPH_CLUSTER_ID: "45d33c5e-afd8-46a9-a989-e02be4af9c7e"
  CEPH_MON1_IP: "10.0.0.81"
  CEPH_MON2_IP: "10.0.0.82"
  CEPH_MON3_IP: "10.0.0.83"
  CEPH_POOL_NAME: "kubernetes"
  # Networking
  INGRESS_TYPE: loadbalancer
  LOAD_BALANCER_IP_RANGE: 192.168.1.100-192.168.1.200
  # Resources - normal for prod
  DEFAULT_CPU_REQUEST: 100m
  DEFAULT_MEMORY_REQUEST: 256Mi

  ONEPASSWORD_CONNECT_HOST: "http://10.2.20.5:7070"
  ONEPASSWORD_VAULT: "k3s-prod"