---
- name: Pre tasks
  hosts: all
  pre_tasks:
    - name: Verify Ansible is version 2.11 or above
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.11', '>=')
        msg: >
          "Ansible is out of date. See here for more info: https://docs.technotim.live/posts/ansible-automation/"

- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  roles:
    - role: common/prereq
      become: true
    - role: k3s/download
      become: true

- name: Setup k3s servers
  hosts: k3s_master
  roles:
    - role: k3s/k3s_server
      become: true

- name: Setup k3s agents
  hosts: k3s_node
  roles:
    - role: k3s/k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: k3s_master
  roles:
    - role: k3s/k3s_server_post
      become: true

- name: Storing kubeconfig in the playbook directory
  hosts: k3s_master
  tasks:
    - name: Copying kubeconfig from {{ hostvars[groups[group_name_master | default('k3s_master')][0]]['ansible_hostname'] }}
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: ../../kubeconfig
        flat: true
      when: ansible_hostname == hostvars[groups[group_name_master | default('k3s_master')][0]]['ansible_hostname']