---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-cluster-settings
  namespace: flux-system
data:
  CEPH_CLUSTER_ID: ""  # To be filled with your Ceph cluster ID
  CEPH_MON1_IP: ""     # To be filled with your first monitor IP
  CEPH_MON2_IP: ""     # To be filled with your second monitor IP
  CEPH_MON3_IP: ""     # To be filled with your third monitor IP
  CEPH_POOL_NAME: "kubernetes"  # Default pool name for Kubernetes volumes