---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ceph-admin-secret
  namespace: ceph-csi-system
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: ceph-admin-secret
    template:
      type: Opaque
      data:
        userID: "{{ .cephAdminUser }}"
        userKey: "{{ .cephAdminKey }}"
  data:
    - secretKey: cephAdminUser
      remoteRef:
        key: ceph-csi
        property: admin-user
    - secretKey: cephAdminKey
      remoteRef:
        key: ceph-csi
        property: admin-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ceph-user-secret
  namespace: ceph-csi-system
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: ceph-user-secret
    template:
      type: Opaque
      data:
        userID: "{{ .cephUserID }}"
        userKey: "{{ .cephUserKey }}"
  data:
    - secretKey: cephUserID
      remoteRef:
        key: ceph-csi
        property: user-id
    - secretKey: cephUserKey
      remoteRef:
        key: ceph-csi
        property: user-key