---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - cluster-settings.yaml
  - storageclass.yaml
configMapGenerator:
  - name: ceph-cluster-settings
    namespace: flux-system
    behavior: merge
    envs:
      - cluster-settings.yaml