---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "${CEPH_CLUSTER_ID}"
  pool: "${CEPH_POOL_NAME}"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: ceph-admin-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-system
  csi.storage.k8s.io/controller-expand-secret-name: ceph-admin-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-system
  csi.storage.k8s.io/node-stage-secret-name: ceph-user-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-system
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate