creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: age1yzc0gc34lxth2dyr4fr42nwuv45ac66r8c26cjredf8gysmrjstqrfw764
  - path_regex: kubernetes/.*secrets?\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: age1yzc0gc34lxth2dyr4fr42nwuv45ac66r8c26cjredf8gysmrjstqrfw764
  - path_regex: terraform/.*\.tfvars
    age: age1yzc0gc34lxth2dyr4fr42nwuv45ac66r8c26cjredf8gysmrjstqrfw764
  - path_regex: packer/.*\.pkrvars\.hcl
    age: age1yzc0gc34lxth2dyr4fr42nwuv45ac66r8c26cjredf8gysmrjstqrfw764