version: '3'

vars:
  ENV: '{{.ENV | default "dev"}}'

includes:
  ansible: .taskfiles/ansible
  docker: .taskfiles/docker
  kubernetes: .taskfiles/kubernetes
  packer: .taskfiles/packer
  terraform: .taskfiles/terraform

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list