---
# Proxmox configuration for prod environment
ansible_user: root

# Basic configuration
proxmox_disable_subscription_nag: true
proxmox_enable_firewall: true
proxmox_remove_old_kernels: true
proxmox_enable_auto_updates: false

# DNS servers (update when DNS servers are deployed in prod)
proxmox_dns_server: "1.1.1.1"
proxmox_dns_server_secondary: "1.0.0.1"

# Network configuration
proxmox_configure_network: true
proxmox_network_config:
  interfaces:
    - name: eno1
      method: manual
    - name: eno2
      method: manual
  bridges:
    - name: vmbr0
      method: static
      address: "{{ ansible_default_ipv4.address }}"
      netmask: "{{ ansible_default_ipv4.netmask }}"
      gateway: "{{ ansible_default_ipv4.gateway }}"
      ports:
        - eno1
        - eno2
      vlan_aware: true
    - name: vmbr1
      method: manual
      ports: []
      vlan_aware: true

# Storage configuration
proxmox_storage_config:
  directories:
    - name: local-backups
      path: /var/lib/vz/backups
      content: backup
    - name: local-isos
      path: /var/lib/vz/template/iso
      content: iso
    - name: local-templates
      path: /var/lib/vz/template
      content: vztmpl

# Cluster configuration
proxmox_create_cluster: true
proxmox_cluster_name: pve-prod-cluster