subsearch_master_key: ENC[AES256_GCM,data:n3avHbDps/cS7XG+CjPgqqKceLKgQIEO4vOe7L1KhHibQ6bqydUzy/9qag==,iv:LY8YlfHW3sBjuEeUC8jlVYDXFBzqfrdMxgh3U2nduP4=,tag:sP994mIWBAviVdg3YueoSQ==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXVwMzVHN1lRVWd1Qytn
            NWtoUG5vdndTTUl0eEZEeXhORXFvTmowQ1hzCmZUUWsrVVJVZEdZQS9LNWxqWWVq
            ZkJBMXhycDRNZ0hWeG1BNVhWZzNtdkkKLS0tIC8xRDBoWVBRV2l1WDVrVWF0REV5
            MkR2VlpCREYrcFNQZ29sdXJVMC9BNzQKMv5pUUcEQCc7hc6HCEQoJVX1bNiIA8gm
            DIGN6AD2XwLLAYTITzm9004momdpGk1EF2WW+K2eGZ6SC9LoD+FAcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T10:34:31Z"
    mac: ENC[AES256_GCM,data:Z1g0e7QGfYa3vYrk9Z3q500vC6iD3Fg8FLaH5uxAhGeudpuLznaGPizIOI70dUeUSMCiBnBkUWJDtZ2h+5cWTERHx40roiHciWYwC7qL7vscmX+XerHWk1glrLp5l5wzvCz7Ub0I4qZkzQJKwsV6qlyOmi0g0nvdmbvVg0pyCBs=,iv:QUuAcSLGWmXkHWQ75y1/A/J84Ng4sdXqKr5nS/AYPJo=,tag:oohBaNvXfQMgSaIoPuaXFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
