apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-restic-template
  namespace: volsync-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: volsync-restic-template
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_PASSWORD: "{{ .resticPassword }}"
  data:
    - secretKey: resticPassword
      remoteRef:
        key: volsync-restic
        property: password