apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-claim-token
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: plex-claim-token
    creationPolicy: Owner
  data:
  - secretKey: claim-token
    remoteRef:
      key: plex
      property: claim-token