apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  selector:
    app: prowlarr
  ports:
  - name: http
    port: 80
    targetPort: 9696
    protocol: TCP
  type: ClusterIP