apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - namespace.yaml
  - helmrepository.yaml
  - onepassword-secret.sops.yaml
  - helmrelease.yaml
  # ClusterSecretStore needs to be created after external-secrets is deployed
  # Moving to a separate kustomization or using Flux dependencies