---
- name: Check if node is already in a cluster
  ansible.builtin.command:
    cmd: pvecm status
  register: cluster_status
  changed_when: false
  failed_when: false

- name: Create cluster on first node
  ansible.builtin.command:
    cmd: pvecm create {{ proxmox_cluster_name }}
  when:
    - inventory_hostname == groups['proxmox_nodes'][0]
    - "'Cluster information' not in cluster_status.stdout"
  register: cluster_created

- name: Get join information from master
  ansible.builtin.command:
    cmd: pvecm expected 1
  delegate_to: "{{ groups['proxmox_nodes'][0] }}"
  when:
    - inventory_hostname != groups['proxmox_nodes'][0]
    - "'Cluster information' not in cluster_status.stdout"
  run_once: true

- name: Join nodes to cluster
  ansible.builtin.command:
    cmd: pvecm add {{ hostvars[groups['proxmox_nodes'][0]]['ansible_default_ipv4']['address'] }} --use_ssh
  when:
    - inventory_hostname != groups['proxmox_nodes'][0]
    - "'Cluster information' not in cluster_status.stdout"
  register: node_joined

- name: Wait for cluster to stabilize
  ansible.builtin.wait_for:
    timeout: 30
  when: cluster_created.changed or node_joined.changed