---
- name: Configure directory storage
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ proxmox_storage_config.directories | default([]) }}"
  when: proxmox_storage_config.directories is defined

- name: Add directory storage to Proxmox
  ansible.builtin.command:
    cmd: pvesm add dir {{ item.name }} --path {{ item.path }} --content {{ item.content | default('images,iso,vztmpl,backup,rootdir') }}
  loop: "{{ proxmox_storage_config.directories | default([]) }}"
  when: proxmox_storage_config.directories is defined
  register: storage_result
  failed_when: 
    - storage_result.rc != 0
    - "'already exists' not in storage_result.stderr"
  changed_when: storage_result.rc == 0

- name: Configure LVM storage
  ansible.builtin.command:
    cmd: pvesm add lvm {{ item.name }} --vgname {{ item.vgname }} --content {{ item.content | default('images,rootdir') }}
  loop: "{{ proxmox_storage_config.lvm | default([]) }}"
  when: proxmox_storage_config.lvm is defined
  register: lvm_result
  failed_when: 
    - lvm_result.rc != 0
    - "'already exists' not in lvm_result.stderr"
  changed_when: lvm_result.rc == 0

- name: Configure ZFS storage
  ansible.builtin.command:
    cmd: pvesm add zfspool {{ item.name }} --pool {{ item.pool }} --content {{ item.content | default('images,rootdir') }}
  loop: "{{ proxmox_storage_config.zfs | default([]) }}"
  when: proxmox_storage_config.zfs is defined
  register: zfs_result
  failed_when: 
    - zfs_result.rc != 0
    - "'already exists' not in zfs_result.stderr"
  changed_when: zfs_result.rc == 0