---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-samuelcalvert-com
  namespace: default
spec:
  secretName: local-samuelcalvert-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.samuelcalvert.com"
  dnsNames:
  - "local.samuelcalvert.com"
  - "*.local.samuelcalvert.com"
