---
- name: Restart step-ca
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/step-ca"
    state: restarted
    recreate: always

- name: Stop step-ca
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/step-ca"
    state: stopped

- name: Start step-ca
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/step-ca"
    state: present
