apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cluster-settings.yaml
  - infrastructure-controllers.yaml
  - apps.yaml

patches:
  # Speed up reconciliation in dev for faster testing
  - patch: |
      - op: replace
        path: /spec/interval
        value: 1m
    target:
      kind: Kustomization
      name: apps