---
ldn_services:
  # Infrastructure
  - name: vm
    backend_host: 10.3.20.10
    backend_port: 8006
    proxied: true
    tls_skip_verify: true
  - name: kvm
    backend_host: 10.3.0.210
    backend_port: 80
    proxied: true
    
  # Monitoring
  - name: grafana
    backend_host: 10.3.20.30
    backend_port: 3000
    proxied: true
  - name: prometheus
    backend_host: 10.3.20.30
    backend_port: 9090
    proxied: true
  - name: homepage
    backend_host: 10.3.20.30
    backend_port: 3002
    proxied: true

  # Haivision
  - name: hmg
    backend_host: 10.3.20.111
    backend_port: 443
    proxied: false
  - name: kr
    backend_host: 10.3.20.248
    backend_port: 443
    proxied: false

  # Apps
  - name: homeassistant
    backend_host: 10.3.20.50
    backend_port: 8123
    proxied: true
    forward_headers: true
