---
# DNS Server (BIND9) configuration

dns_forwarders:
  - "1.1.1.1"
  - "1.0.0.1"

dns_trusted_networks:
  - localhost
  - localnets
  - 10.3.0.0/24

# Reverse Proxy IP (used for DNS A records of proxied services)
reverse_proxy_ip: "10.3.0.80"

# Reverse DNS zone name (derived from subnet)
dns_reverse_zone: "0.3.10.in-addr.arpa"

# Reverse Zone PTR Records
dns_ptr_records:
  - octet: "9"
    hostname: "ca.ldn.5am.cloud."
  - octet: "53"
    hostname: "dns.ldn.5am.cloud."
  - octet: "80"
    hostname: "caddy.ldn.5am.cloud."
  - octet: "30"
    hostname: "monitoring.ldn.5am.cloud."
