apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: https://10.1.20.222:6443
  name: dev-cluster
contexts:
- context:
    cluster: dev-cluster
    user: dev-user
  name: dev
current-context: dev
kind: Config
preferences: {}
users:
- name: dev-user
  user:
    client-certificate-data: redacted
    client-key-data: redacted