apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token-externalsecret
  namespace: cert-manager
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: kubernetes-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
    creationPolicy: Owner
  data:
  - secretKey: cloudflare-token
    remoteRef:
      key: cloudflare-token-source
      property: cloudflare-token