apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token-externalsecret
  namespace: cert-manager
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: 1password  # Use the 1Password store
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
    creationPolicy: Owner
  data:
  - secretKey: cloudflare-token
    remoteRef:
      key: "Cloudflare API Token"  # Name of the item in 1Password
      property: token              # Field name in 1Password