vault_haivision_vpn_user: ENC[AES256_GCM,data:hRMJPbQ+MSQ=,iv:ULlkfld3TW3vd5HdlJ+BVDTBFqskhYjKR8IZ+pLvFB4=,tag:iS1LQR1z3IIY0XIcKTp6UQ==,type:str]
vault_haivision_vpn_password: ENC[AES256_GCM,data:HeS5X03I9TwgA8pXRnTqfw==,iv:OgACNSKEMCSGMy/xrtFk8gS2wJp30GYiwhGz8OjMNkY=,tag:LdL5qrAXkn/RnIEk21a9aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eGVvQkNmSHFJR3RiRmNJ
            cW01SkUrZkcxekowRUFSOWlBR2xqeGFUcGtjCnNhak03aTMyNW9hbEliT3A5ckR0
            ejY5ak1iaXRUR0U1MnNJbVord1pOQ2cKLS0tIHpNTlBnWWQ0aVJTTlJTYkZPcUFq
            dkY1Z2sycHpFSFkvc0k0YkhxRFJCRVkKGMvvGxetx5Opu2datjEx+9UbHk1B6HY+
            meayjXJaCvv76FylI/GXPbJhTGhXSEz4Umv/2O+TgbFNLmq5aMANLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
    lastmodified: "2026-08-05T15:04:23Z"
    mac: ENC[AES256_GCM,data:bpvKjhgU5ZQLZQeXsRuY74uijlPSWuMELcLtcY82wbRuQYW0sBB9EQbA9g6ya1bCmYGgsL7SqMYe34Z+TdJi1JIGPmCp02eCRyAacKCXCtUpnfPbpwHGZSs/ElNrvh8PPWus3x2VZU+TqsCj+LUf5QY969fq4Pc2KItb+Q/PZL0=,iv:3oT8GeR2RHqjFhCXmqNyRu69aBtAY9hY3F9actjqawU=,tag:ZoExSGkwUAzVZufXoSwKWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
