version: '3'

vars:
  ENV_DIR: 'environments/{{.ENV}}'

tasks:
  deploy:
    desc: Deploy all infrastructure for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - echo "===================================="
      - echo "Deploying all infrastructure for {{.ENV}} environment"
      - echo "===================================="
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform apply -auto-approve

  deploy-k3s:
    desc: Deploy only K3s cluster for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - echo "===================================="
      - echo "Deploying K3s cluster for {{.ENV}} environment"
      - echo "===================================="
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform apply -target=module.k3s_cluster -auto-approve

  deploy-dns:
    desc: Deploy only DNS server for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - echo "===================================="
      - echo "Deploying DNS server for {{.ENV}} environment"
      - echo "===================================="
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform apply -target=module.dns_server -auto-approve
  
  deploy-docker:
    desc: Deploy docker server for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - echo "===================================="
      - echo "Deploying DNS server for {{.ENV}} environment"
      - echo "===================================="
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform apply -target=module.docker_vm -auto-approve

  destroy:
    desc: Destroy all VMs and infrastructure for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - echo "===================================="
      - echo "DESTROYING all infrastructure for {{.ENV}} environment"
      - echo "===================================="
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform destroy -auto-approve

  clean:
    desc: Clean up all Terraform files for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - echo "Cleaning Terraform files for {{.ENV}}..."
      - rm -rf {{.ENV_DIR}}/.terraform
      - rm -f {{.ENV_DIR}}/.terraform.lock.hcl
      - rm -f {{.ENV_DIR}}/terraform.tfstate*