version: '3'

vars:
  ENV_DIR: 'environments/{{.ENV}}'

tasks:
  deploy:
    desc: Deploy all infrastructure for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform apply -auto-approve

  deploy-vm:
    desc: Deploy specific VM for {{.ENV}} environment (requires VM=vm-key)
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform apply -target='module.infrastructure.module.vms["{{.VM}}"]' -auto-approve

  destroy:
    desc: Destroy all VMs and infrastructure for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform destroy -auto-approve

  destroy-vm:
    desc: Destroy specific VM for {{.ENV}} environment (requires VM=vm-key)
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - cd {{.ENV_DIR}} && terraform init
      - cd {{.ENV_DIR}} && terraform destroy -target='module.infrastructure.module.vms["{{.VM}}"]' -auto-approve

  clean:
    desc: Clean up all Terraform files for {{.ENV}} environment
    dir: '{{.ROOT_DIR}}/terraform'
    cmds:
      - rm -rf {{.ENV_DIR}}/.terraform
      - rm -f {{.ENV_DIR}}/.terraform.lock.hcl
      - rm -f {{.ENV_DIR}}/terraform.tfstate*