services:
  yolo-model-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo-model-generator
    volumes:
      - ./models:/host-models
    command: |
      sh -c "
        cp /output/yolo_nas_s.onnx /host-models/
        cp /output/coco-80.txt /host-models/
        echo 'Model files copied successfully!'
        echo 'Files in output directory:'
        ls -lh /host-models/
      "