---
# Prometheus retention
prometheus_retention: "30d"

# Prometheus scrape targets
# Add hosts here to have node-exporter scraped from them
prometheus_node_targets:
  - "localhost:9100"   # local (monitoring VM)
  - "10.3.0.53:9100"  # dns
  - "10.3.0.80:9100"  # reverse proxy
