bookstack_db_password: ENC[AES256_GCM,data:jWbX4UN6ojM=,iv:fhwePFUhnLk6GvahWyNZyneDlLF2DujjjhSqUPYxrGY=,tag:ZEBq9vjZ8PT9GO1NY8pSJA==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaDFmS3hvUzZPZUo2RWFw
            cE1QM3dZQ1U5WDFTSEJGL25LUmpPU0ZNeUFFClpIRjdxUi9kUldCMDFnVU55WVlO
            bGFGRXZSb0Zjc25IZ3EzMTc2alBVbEEKLS0tIEpOSTVzTmNSWDA1d1RBU1BaYmxX
            anB3aDZmOGRqSFQxMFdyT2Y5TjlKVmMKeoEKQC/D+SXHBs3n16puuX6wme0ED4qB
            rvWzPBhogQ/e8+PsURVP+RppGyb49kzAUAa/HMS/lfaYmqGSAay72g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T21:21:49Z"
    mac: ENC[AES256_GCM,data:gNaXSYeHhcFZXZBpzTJmpb7DhTBnbNhjpwvso0jigXOmQVH4XScvaY3m4Pj1HZbmxpZnO2i0iGJee2PhK6JfsOlmk1/qAiBjqQPC+ZQi514jhG+JNJh616fLQqZLSuHLMhPfGep2kKZhZUID6ewqlnp1/NW8x8ehvLzVHzfGaRA=,iv:eUk4doJRhwf84vPtZsnle7PaxclGHtYK2fakY2zk4TY=,tag:xsFNyG5c56ywOZtEcyo4DA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
