apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: intel-device-plugins-system
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  values:
    manager:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-01