vault_haivision_vpn_user: ENC[AES256_GCM,data:hRMJPbQ+MSQ=,iv:ULlkfld3TW3vd5HdlJ+BVDTBFqskhYjKR8IZ+pLvFB4=,tag:iS1LQR1z3IIY0XIcKTp6UQ==,type:str]
vault_haivision_vpn_password: ENC[AES256_GCM,data:sNapLj3rU/KUlaZRMf6z,iv:kGNrqdHG0sqEMYehEa4l44xrV7ewNwR1QuNXPaGdBRs=,tag:tIrxiWYahra2n7Ex3q2duw==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eGVvQkNmSHFJR3RiRmNJ
            cW01SkUrZkcxekowRUFSOWlBR2xqeGFUcGtjCnNhak03aTMyNW9hbEliT3A5ckR0
            ejY5ak1iaXRUR0U1MnNJbVord1pOQ2cKLS0tIHpNTlBnWWQ0aVJTTlJTYkZPcUFq
            dkY1Z2sycHpFSFkvc0k0YkhxRFJCRVkKGMvvGxetx5Opu2datjEx+9UbHk1B6HY+
            meayjXJaCvv76FylI/GXPbJhTGhXSEz4Umv/2O+TgbFNLmq5aMANLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T14:38:58Z"
    mac: ENC[AES256_GCM,data:OuoYGQtOJvEltvuhJgSNFh4c0Lf5Mv4sSIqbh8ImSMZKz37WT3rzjZ1AW7hn0U7ZOnIWFZoyxySCgZY3jdYEVgV6qNRwIxtTo1WHRyvCBrNNcRljK/RFQDvJr1dVr+uuMOcVOSxiY8j2I6xSdtEKBHE7u85UZ3757/8vAGic2Ak=,iv:dLbsFn9tOlclKFE5FjzzqfTKRAcx+zv8rJx3uMQLXMQ=,tag:s97lotfKZ1ifkb70O05v+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
