# ansible/roles/proxmox/cluster/tasks/main.yml
---
- name: Create Proxmox cluster
  when: cluster_action == "create"
  block:
    - name: Create new cluster
      ansible.builtin.command:
        cmd: pvecm create {{ proxmox_cluster_name }}
      args:
        creates: /etc/pve/corosync.conf

- name: Join Proxmox cluster
  when: cluster_action == "join"
  block:
    - name: Get join information from primary node
      ansible.builtin.setup:
        gather_subset: all
      delegate_to: "{{ groups['proxmox_primary'][0] }}"
      register: primary_node_facts

    - name: Add node to cluster
      ansible.builtin.command:
        cmd: pvecm add {{ primary_node_facts.ansible_default_ipv4.address }} --force
      args:
        creates: /etc/pve/corosync.conf