---
- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"

- name: Add Proxmox repository key
  ansible.builtin.apt_key:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    state: present

- name: Add Proxmox repository
  ansible.builtin.apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/pve bookworm pve-no-subscription"
    state: present
    filename: proxmox

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Proxmox VE packages
  ansible.builtin.apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
      - zfsutils-linux
    state: present

- name: Remove os-prober package to prevent issues with PVE
  ansible.builtin.apt:
    name: os-prober
    state: absent

- name: Enable required services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - pve-cluster
    - pvedaemon
    - pveproxy
    - pvestatd