step_ca_provisioner_password: ENC[AES256_GCM,data:o3kCQMPlZ7H15Yed96cOcUYVsdXS5IbAhO9nehl2IoFdwu7206r1ZtBc8K4=,iv:mFagaM+snf3jb7ymgJejijjf3G3w27IaxrVcn2Qm/Ok=,tag:1Vw5WboT8OVOiePjJrbf/A==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScmE3MmdmazMyemZRZlJH
            Y1hLVEVNaXhqRER6VHlRbUtKekFJeXY1aUZzCmlCNXJHbFl4RlRlcFRIS3BFMGl6
            ZFVDTm50Kzh0TzNBZkM0QTlyMEtLN3cKLS0tIG9aaExtcXp6TDlYVHlNcEZZeWk3
            RUV0cTFZMFJEUVhMUWZ2WCtSOWhZencKlUjUNxzrfDsJwufJlElO6wbsSIxsceob
            UIOH1SmxUjIlhdcvvQR1K8CSS1ojAgfO8LwLV4RdWw0esnYuOmY/CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T17:49:32Z"
    mac: ENC[AES256_GCM,data:uxe3pBpeYLQ9cB+gm/wW8uSImc3pgiwp4V/aYy2oJtvCOqdY0BaIwesKACy4m9mGzqM/1ea4Gfm/pkXGtgEj4oN4gYi1lWZtKQT98sn8xCGShAlUDMlc6zMtvI4T2WZDC7mk1K3OfTbfavoLE7HmowXPxbnhkKVRqJzUHTH2zys=,iv:+efjqGOPfF7woLhMfRAfNP+xfOfXlj9Uy3kw6iHBjKo=,tag:adFWJjMZXhSMIPMzcPg1Dg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
