apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-ceph-blockpool
driver: rbd.csi.ceph.com
parameters:
  clusterID: "${CEPH_CLUSTER_ID}"
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: ceph-csi-system
deletionPolicy: Delete