---
services:
  bind9:
    container_name: nyc-dns-01
    image: ubuntu/bind9:9.18-23.04_edge
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    volumes:
      - ./config/:/etc/bind:rw
    network_mode: host
    restart: unless-stopped