---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-samuelcalvert-com-staging
  namespace: default
spec:
  secretName: local-samuelcalvert-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.samuelcalvert.com"
  dnsNames:
  - "local.samuelcalvert.com"
  - "*.local.samuelcalvert.com"
