---
- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Reload bind9
  ansible.builtin.service:
    name: bind9
    state: reloaded

- name: Check bind9 config
  ansible.builtin.command: named-checkconf
  changed_when: false

- name: Restart cloudflare-ddns
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/cloudflare-ddns"
    state: restarted

- name: Rebuild caddy
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/caddy"
    build: always
    state: present

- name: Restart caddy
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/caddy"
    state: restarted

- name: Restart openvpn clients
  ansible.builtin.service:
    name: "openvpn-client@{{ item.name }}"
    state: restarted
  loop: "{{ vpn_clients | default([]) | selectattr('enabled', 'equalto', true) | list }}"
  loop_control:
    label: "{{ item.name }}"
