# This file defines how Flux syncs with your Git repository
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system # SSH key for private repositories (if needed)
  url: https://github.com/sfcal/homelab.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
