installCRDs: false
replicaCount: 3
extraArgs:
  - --dns01-recursive-nameservers=8.8.8.8:53,9.9.9.9:53
  - --dns01-recursive-nameservers-only
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 8.8.8.8
    - 9.9.9.9
