apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-01
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        ports:
        - containerPort: 32400
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        - name: VERSION
          value: "docker"
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: plex-claim-token
              key: claim-token
              optional: true
        - name: TRANSCODE_DIR
          value: "/transcode"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /tv
        - name: movies
          mountPath: /movies
        - name: dri
          mountPath: /dev/dri
        - name: transcode
          mountPath: /transcode
        resources:
          requests:
            memory: "8Gi"
            cpu: "3000m"
          limits:
            # Increase memory limit to account for RAM transcode directory
            memory: "16Gi"
            cpu: "4000m"
        securityContext:
          privileged: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - name: tv
        nfs:
          server: 10.2.10.100
          path: /mnt/NAS-WIL/Media/media/tv
          readOnly: true
      - name: movies
        nfs:
          server: 10.2.10.100
          path: /mnt/NAS-WIL/Media/media/movies
          readOnly: true
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: transcode
        emptyDir:
          medium: Memory
          sizeLimit: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 50Gi