apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-secrets
  namespace: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: frigate-secrets
    creationPolicy: Owner
  data:
  - secretKey: rtsp-password
    remoteRef:
      key: frigate
      property: rtsp-password
  - secretKey: mqtt-password
    remoteRef:
      key: frigate
      property: mqtt-password