---
- name: Deploy Networking (DNS, Reverse Proxy, Tailscale)
  hosts: infra_networking
  become: true

  handlers:
    - name: Include various service handlers.
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_role:
        name: common

  tasks:
    - name: Configure Tailscale.
      ansible.builtin.include_role:
        name: tailscale

    - name: Configure BIND9.
      ansible.builtin.include_tasks: tasks/bind9.yml

    - name: Configure Cloudflare DDNS.
      ansible.builtin.include_tasks: tasks/ddns.yml

    - name: Configure Caddy.
      ansible.builtin.include_tasks: tasks/caddy.yml
