seafile_db_password: ENC[AES256_GCM,data:UA11sJOYS810jKdvRNngySA7U7AEGbZc4Vohog6nnbfYvVE=,iv:0U1+XPMjpDQeB20EcXztGAZKuUwdrytsbJssJUTHfTU=,tag:ISeSxjWhcqvzeZ2TnMrUYw==,type:str]
seafile_admin_email: ENC[AES256_GCM,data:CiMjDQNhuRMBhCIek2OL,iv:R4H8eHCnk6R1YqnU1PycfY4FvyeETV/THE38qYv/Sv4=,tag:M7OaIuxXrJz6qvzh/DSQ0A==,type:str]
seafile_admin_password: ENC[AES256_GCM,data:QMAwPE5RSD7z5Ono2nIKchX/X8/1Lw8MS5VlZU0VfydIycw=,iv:bpUISsDkeJAkw+BwapY4ldd9ZpmTuCu4hnBybsarih4=,tag:SUEI8AkF9/3rrBU9r+VyMA==,type:str]
seafile_jwt_key: ENC[AES256_GCM,data:jQ1VjsPxZ4xOx5qQV7uf8NVoHvA124R4AlOGhQ5SJ1Bdtd4T0O8JP9QfpmdaRr+1UeZyUaxAI/qYYNH/CES/Jw==,iv:r4WrsA4DZOqi8jrXqmLAt7prdPyrBo+J9gD6aMZbnlQ=,tag:ffuFKoO8Bzat7TNdqIQfcA==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK3N0ZGVWV2xFT0xIU2I4
            VWN1eVM1djF6MktYdEFYMU9HNkppRFl6ODA4CmVvMUZmdU0wMVdyUlc5NC83T2Rs
            MlVnN25RZk1SQmVxa0dGZVFnaTJ2TGMKLS0tIHErZTk5UmVQT2hiNml5eW8vR0Ux
            Y1diSEZHVHQrWWZENlBzcmllZWp2MUUKMgEp6j8FFtrPkOAUCgkgJ0DImbymt4SF
            C/1K/1PS0vqpnJxUWl0ItUB/mYKN88W1nyVjIo81B//ErE24VjRHNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T23:37:41Z"
    mac: ENC[AES256_GCM,data:7ciEvmYYkn05mtp5LfTcRxQRATBmUOmog9nbMb12sNO+p+AJlLLfwKXhwkuaIn/yHir9I02WPgvq/kzftQWZpWe7cVRPdoYHJseL7nRBTl2kkJ2HII4DVCRAL7ByPvqrbgV/wO8ID5WhLDgQgMmxFHm9JwV9+WMYO5uoP7UldN0=,iv:WU6K0GaVq5cY+hl1pTgmn001faci30Kv09HNc8P/A5I=,tag:G6MpRcrqOPJtwE/MoFddhw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
