---
seafile_image: "seafileltd/seafile-mc:11.0-latest"
seafile_db_image: "mariadb:10.11"
seafile_memcached_image: "memcached:1.6.29"
seafile_port: 8080
seafile_user: root
seafile_group: root
seafile_hostname: "files.wil.5am.cloud"
