birdle_secret_key: ENC[AES256_GCM,data:nPhysDWworyoIGSbYYq+mMEInJmE8G+9YLIRTMEwU8EeeV57IOd2/TgvzWsuHeOZSil48lGAL2Zz8eorThGPNhuTYA==,iv:b5tGxsUpM3/ubZpxV7pXGfWPY4O8EmekAHlbmKD6XRk=,tag:CKbccWRPNc6CFyhHfbEobg==,type:str]
birdle_db_password: ENC[AES256_GCM,data:Gw1eJl3VK6TiGoRzjjoZYtgEg0Y0gkSPQ/NGaNGtr3g=,iv:qSAIvwBwyRHBcFzCwqHN+CO7mZwsck+pbKClZJrXyYg=,tag:cr7zN6R42haF8BgbYp8yoQ==,type:str]
birdle_ebird_api_key: ENC[AES256_GCM,data:rby/uyibrwSJT1hT,iv:2qEdKa/SeIeW7UqQalFbCX6HzjsepO43DUupcMaerWM=,tag:MfrzqYttXfT4aHzjYnKp/g==,type:str]
bookstack_db_password: ENC[AES256_GCM,data:X8Yp1/FRskI=,iv:TRjIP92MJq91yBG20sU4P/I5eDJme+yFqdgdP8tJN8A=,tag:XDXLfFGVCpqL1zRi5+PUiA==,type:str]
convertx_jwt_secret: ENC[AES256_GCM,data:RvMc7zOWyqfArFGs0mvlmPSfEV6Nr6Ywq6ZQ7jRh8ZJ6dMxW2NuMztLemkgcXpVRbxwRUco6d3lHvxLs4BykKQ==,iv:wIYy019EpC51drVz2t92kY9EaoT0QFKzn/MVDHezbZg=,tag:ZoqpYZyquQeisxgEPqiZDA==,type:str]
#ENC[AES256_GCM,data:EOmstz2miFAXlVnOwhn7Z3V3S9rsuSJ6,iv:Q6sK/yrd2FsqwFOwhmy/v1mekJtsAKIsKCD++SMY6Ys=,tag:l57/jU45D3XpjfOLDRUEqw==,type:comment]
terraria_server_password: ENC[AES256_GCM,data:eaPt,iv:k4UQw/3aaJdoHWrHbt6VreLZNFmyAWkrvNzCSoSpixY=,tag:u40ZOTO1slPHPgZgOE9/PQ==,type:str]
romm_db_root_password: ENC[AES256_GCM,data:mzZiP0tbI4nd//5cbmVCuaM3Ou+qUg==,iv:/GjXBprxNo0vqhYwLqGU8qE2HSHjt3HrVkUoOFvMgdE=,tag:Uzld1py/jkhL2zFWFtzwhA==,type:str]
romm_db_password: ENC[AES256_GCM,data:tVPxsSjV1+qFNB9WCnQ438QJUArHjg==,iv:LoA3xXM0lm3mNby5Xje+T1yqf39NUCfllwZDtMkLHS8=,tag:xAyMoOFehBnwTwglLPMaYQ==,type:str]
romm_auth_secret: ENC[AES256_GCM,data:wjXWvRBia2dAFGLAkzvpqRvdVBpf4wsfnI5KkdXy4IAqnZUBSDM8vI3n1g==,iv:4isWCBlYrje84B5Pq1PRyAE8aS6C57h842lZ9M/WZEQ=,tag:X2/LU/ZK2uyi2MAduB6WXg==,type:str]
romm_igdb_client_id: ENC[AES256_GCM,data:B48lqHWlaX1YBGEzukEHxiGNkuQPB4ZOLHbvu4Bo,iv:0K4QoD8OLcQGIK30Fw4v0ig5y8mC9kL4/LDLYgxKNfM=,tag:ebd1IaQyOdzUcPlDqUmUzA==,type:str]
romm_igdb_client_secret: ENC[AES256_GCM,data:yZ8YgBpnq3UGyYb8MZ3xurIo61JHc3Mb50DvYMyk,iv:dm3R6kwqWvudYiyxZFCtTWHn9KMQPvMRJu/+K9SP4gE=,tag:fvHjf2BhWH0gktRhnNE0FA==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU09UdGh0RlBGV1EyblNZ
            UlNZMENINFZSY3ducjUzdkVLd1ZXVjdQbEc4Cm1MVmNLeXR0bncxV3Fpamhzc3Jp
            YUFGekxlb0lDZGRJUmdoTHNvV3NXd2MKLS0tIFJDdkhoZXF0eHVNQmVPNUNsNXlH
            OVlKZXdhclUySy9kaWZqU0luQmh2K0EKzjqnbTprMspfEXeEPbrJYatdLINjU2lB
            u5cJv1weWwUl4OFUY2ubCuPM+xQVi2zAfxE8IjGMEd1+auctN2O5CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T10:51:24Z"
    mac: ENC[AES256_GCM,data:Ks6Xp829K+vABp+gLyXjNXKvTtRrvT874F65Kr9Jnx3Lx5ZBhty52Mi4yQdcciaoi0NE07ntkJVs8O1KpnNaWzI/EKBi7Z9fQ/5PFy4FFof08NYHI6sncKeSeMpRxOTK3vZ1pBLqTRTTXzzVgrjJHHbvc2kqmb7zEfD7GgiuD70=,iv:ThrJ23FMBgjpEkgKLQLLOclAQwKoaqduHTB8veuTSyU=,tag:2TIJnQE+VXPiqkzoa5yTjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
