---
- name: Deploy Stirling-PDF
  hosts: app_stirlingpdf
  become: true

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_role:
        name: common

  roles:
    - role: docker_service
      vars:
        service_name: stirling-pdf
        service_compose_template: "{{ playbook_dir }}/templates/compose.yaml.j2"
        service_user: "{{ stirlingpdf_user }}"
        service_group: "{{ stirlingpdf_group }}"
        service_images:
          - "{{ stirlingpdf_image }}"
