---

- name: Check if kubectl binary exists.
  stat:
    path: "{{ kubectl_bin_path }}"
  register: kubectl_check

- name: Check kubectl version.
  command: "{{ kubectl_bin_path }} version --client"
  failed_when: false
  changed_when: false
  register: kubectl_existing_version

- name: Download kubectl binary
  get_url:
    url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/{{ k8s_platform }}/{{ k8s_arch }}/kubectl"
    checksum: "{{ kubectl_checksum_binary }}"
    dest: /tmp
  when: >
    not kubectl_check.stat.exists
    or kubectl_version not in kubectl_existing_version.stdout
  notify: copy kubectl binary
