---
- name: Install chrony.
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Customize chrony configuration.
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/chrony/conf.d/{{ item }}"
    mode: 0644
  notify: Restart chrony
  with_items:
    - allow.conf
    - refclock.conf

- name: Ensure chrony is running.
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true