step_ca_provisioner_password: ENC[AES256_GCM,data:0itCufPrGPrVh6r32n/kVxitU/8u24TpcZfOTzD7FhS3eYas4slFcqQ1j3U=,iv:FP7C5VnFjqAJ0SzxFwso1+IEtjJnbzegvLbyLe6aqHg=,tag:sISxqGSYogLq3KluEe6pGQ==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbkpxZWtMYjVvK2ZvR1lx
            MElLd28rMElUNGFBN1dNY2lBUHdMa0dnVVVVCjJMWmJIYnNUTmovOXZWRzNGdmJJ
            OVArcWFvd3FPNnZLWHU1cXFTZ09uUWcKLS0tIHhzTHpScjZoWnFnQjBHWUZSZ254
            WitSUUJGR2FCNVRyNDc2QWdNbHJKSEkKH5Y3U+w9m1V/nt9CjIjqE2nTXXm+oET0
            llHSDvSVv9lROeHh4m4ewf0ABYzd2wYIvmmsgXmf9f6ayk3RQo23GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T12:05:01Z"
    mac: ENC[AES256_GCM,data:z51hKFJaQXZEpg+uB1GZxR/f2jriSxqeRCpcEK6TN9YtIm8BJ7PWwSd6rRN63pFyP8KRSaCC0Vqo0FaF1HnSts+UFeQEEw8EYkO++l+7t5VotMNfaIHyNLnnFcmEW/Z+FT2tjJI1MfS0WxFi/v8B+XOxD7kTykul2CxruDx9Mf0=,iv:l7Ac6p6vj9FsuZnv5m3p1/CR6FEEc5j91X5D0HNzUEs=,tag:A79l0/aGCPoWLsJ75l0BvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
