apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: 1password-connect
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: "1.15.1"  # Check for latest version
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
  values:
    connect:
      serviceType: ClusterIP  # Don't expose externally
      credentialsName: "onepassword-connect-secret"
      credentialsKey: "1password-credentials.json"
    operator:
      create: false  # We're using External Secrets Operator instead