apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      server:
        # When deploying on Kubernetes use this:
        url: "https://kubernetes.default.svc.cluster.local"
        # Use nil for namespace to indicate cluster-wide access 
        namespace: "external-secrets"
      # Auth moved to the same level as server
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets