apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      server:
        url: "https://kubernetes.default.svc.cluster.local"
        caProvider:
          type: ConfigMap
          name: kubernetes-api-ca
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets