apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      server:
        # When deploying on Kubernetes use this:
        url: "https://kubernetes.default.svc.cluster.local"
      # Namespace moved to correct level
      namespace: "external-secrets"
      # Auth at same level as server
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets