apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password-connect.svc.cluster.local:8080
      vaults:
        k3s-dev: 1  # Primary vault to check
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets