apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      server:
        url: "https://kubernetes.default.svc.cluster.local"
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets