---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - sudo
      - net-tools
      - wget
      - htop
      - iotop
      - iftop
      - ntp
      - lsb-release
    state: present

- name: Ensure hostname is set correctly
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"

- name: Update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: '{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ inventory_hostname_short }}'
    state: present

- name: Check if system is using systemd-resolved
  ansible.builtin.stat:
    path: /etc/systemd/resolved.conf
  register: systemd_resolved

- name: Configure systemd-resolved if present
  when: systemd_resolved.stat.exists
  block:
    - name: Disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false

    - name: Remove systemd-resolved symlink
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent

    - name: Create new resolv.conf
      ansible.builtin.copy:
        content: |
          nameserver {{ proxmox_dns_server | default('1.1.1.1') }}
          nameserver {{ proxmox_dns_server_secondary | default('1.0.0.1') }}
        dest: /etc/resolv.conf
        mode: '0644'