apiVersion: v1
kind: Secret
metadata:
    name: onepassword-secret
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:tWwOY7f3AL+j/7kYNzEgYtnVhp+jsBX3yUfMi3tWP7hEp3rZXK3rMTsDvDSPQ+PoCwBAwSqelzwoaNdtpg2drX1CQq0+/N1bhvuxeRDE7xt/aS0SBvrtJjiofvrezWOJW1u1Q4PxV7QQs3vjFXpYdMQgdDSMJJtHyWRJL5Mpbe3oJp2M+N6oyRVkDWD0e7vdtgTngfPEN9K+Q8/vTfJh5uSRzkozJa6xn0t5hfH/FZRcXuF14pwYAEOECRGs5jGMRygx9K4wY/5nV5oIyYbd/tVYSHuJ2Jq7DuMcpWirJwgBaaUI/fch66ZJ1Uldk1R8aXbA5Q4+MGZTXcHODyZuv3Wz99AYZIPIGcKNqYXiXR7c5SfjD11LSoDu6JjUrln0Nf6ErB0WZFlB+tvqPoYr0lY6MyND7BKvXhciMQBqhQ/BBMSFHjsuCx6d5hA4h7qW7ywyuZBRzppXoX7szhjtyJ3FsVUfGfFJcYN0c6Nj1yfrLdzYAUM4H1KStgXpXgUcVLLqUHSoMv7/6LygELcS/DIhaBnO+peZmQ0X0WbhhfwcjDoZNvtCEuvDsa3bojQlMz+ZZdxwiEp1UTpoc+MdqpMzbOZez47DvlZ7PBlnABGVWpfZwGZ4pZ5C/6USUlCBdFCgNx7NstNbrGSj9ZL/1xC5CbSwI4vNTKRFuIMhbRVrcPDzn7cZaetC4RlzdNizZEmvD8xtMTK9dsgdTkOnt2TLT0SEuTTmqwF7fdfONCap1WpgDXcuLZIzbIwbRRg+cZUc1EYDd1geY8BdTs7d4FZS0R8995s1AnHCcD5bmiNZhPbm/AKBxotNATpKvShT+3k/WnEJtA6xPICHcBb13HJ3,iv:f2oyV8j53TZaYyy2tv8SOefO6aZRbI47PJhs+U+u4yU=,tag:xN1vTk8zYxOT/+eg74Jp+A==,type:str]
sops:
    age:
        - recipient: age1yzc0gc34lxth2dyr4fr42nwuv45ac66r8c26cjredf8gysmrjstqrfw764
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTnZJOTRDSENtR3ZrZG51
            Yzc3R05rdGF5YkRlZEFjTWpTMEFKR05pMTFZCmphTVVFVHlqcVVmcVBYUVlkVzlQ
            dlJnRFgwMmQ2cU0xYkRkWTVEOWc3RVUKLS0tICtydm9zRTVGa1paMlY3TG14QmVu
            bUl4T2pXZVhUUHRoeGZndUQ1RW83RlEKC+kUoje1EYeR1aqqX2MN1aqkB4T5BpFU
            pbGik8/HxN82PngRnEDgRjsAb5BHVtx9BTzXccT0i/7QpXkL5wq8yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T17:45:40Z"
    mac: ENC[AES256_GCM,data:+rJqGUd+L24/k1uFRA4a5wtpNLlqTE6LkjF8bLCTOMlkE4B6KYH4I696TJc8qBuhPngFI67dikjgOzHrqzORb/8+AdiAJDJRUb2eGYJo8W2Jwcs0MrlALwfbtCZhintvQHzxnaSvk66wIXxSjXN11TJsqT52FhBdeMhXLOJsFVk=,iv:xrZt83sc0ixoMr4YFhuraZXQV1tHZ2v++uQhJRbYWqY=,tag:euQd/2FBKdDcGW8n39mBjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
