---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "v1.16.2"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    podLabels:
      app.kubernetes.io/part-of: cert-manager
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
    webhook:
      podLabels:
        app.kubernetes.io/part-of: cert-manager
    cainjector:
      podLabels:
        app.kubernetes.io/part-of: cert-manager
    startupapicheck:
      podLabels:
        app.kubernetes.io/part-of: cert-manager