version: '3'

vars:
  TEMPLATE: '{{.TEMPLATE | default "base"}}'
  ENV_VAR_FILE: 'environments/{{.ENV}}/variables.pkrvars.hcl'
  CRED_VAR_FILE: 'environments/{{.ENV}}/credentials.{{.ENV}}.pkrvars.hcl'

tasks:
  build:
    desc: Build a specific template
    dir: '{{.ROOT_DIR}}/packer'
    vars:
      TEMPLATE_FILE: 'templates/ubuntu-server-{{.TEMPLATE}}.pkr.hcl'
    cmds:
      - echo "===================================="
      - echo "Building {{.TEMPLATE}} template for {{.ENV}} environment"
      - echo "Using environment vars {{.ENV_VAR_FILE}}"
      - echo "Using credential vars {{.CRED_VAR_FILE}}"
      - echo "===================================="
      - echo "Initializing Packer plugins for {{.TEMPLATE_FILE}}..."
      - packer init {{.TEMPLATE_FILE}}
      - echo "Building template {{.TEMPLATE_FILE}}..."
      - |
        PACKER_LOG=1 packer build \
          -var-file="{{.CRED_VAR_FILE}}" \
          -var-file="{{.ENV_VAR_FILE}}" \
          "{{.TEMPLATE_FILE}}"
      - echo "Finished building {{.TEMPLATE}} template for {{.ENV}} environment."

  clean:
    desc: Clean up Packer artifacts
    dir: '{{.ROOT_DIR}}/packer'
    cmds:
      - echo "Cleaning up Packer artifacts..."
      - rm -f packer.log
      - rm -rf downloaded_iso_path