version: '3'

vars:
  TEMPLATE: '{{.TEMPLATE | default "base"}}'
  ENV_VAR_FILE: 'environments/{{.ENV}}/ubuntu-variables.pkrvars.hcl'
  CRED_VAR_FILE: 'environments/{{.ENV}}/credentials.{{.ENV}}.pkrvars.hcl'

tasks:
  # Generic build task
  build:
    desc: Build a template
    dir: '{{.ROOT_DIR}}/packer'
    vars:
      # Set defaults based on DISTRO
      TEMPLATE_PREFIX: '{{.TEMPLATE_PREFIX | default "ubuntu-server"}}'
      VAR_FILE: '{{.VAR_FILE | default .ENV_VAR_FILE}}'
      TEMPLATE_FILE: 'templates/{{.TEMPLATE_PREFIX}}-{{.TEMPLATE}}.pkr.hcl'
    cmds:
      - echo "===================================="
      - echo "Building {{.TEMPLATE_PREFIX}}-{{.TEMPLATE}} template for {{.ENV}} environment"
      - echo "Using environment vars {{.VAR_FILE}}"
      - echo "Using credential vars {{.CRED_VAR_FILE}}"
      - echo "===================================="
      - packer init {{.TEMPLATE_FILE}}
      - |
        PACKER_LOG=1 packer build \
          -var-file="{{.CRED_VAR_FILE}}" \
          -var-file="{{.VAR_FILE}}" \
          "{{.TEMPLATE_FILE}}"

  # Distribution-specific tasks
  build-ubuntu:
    desc: Build Ubuntu template
    cmds:
      - task: build
        vars:
          TEMPLATE_PREFIX: ubuntu-server
          VAR_FILE: 'environments/{{.ENV}}/ubuntu-variables.pkrvars.hcl'


  build-debian:
    desc: Build Debian template
    cmds:
      - task: build
        vars:
          TEMPLATE_PREFIX: debian-bookworm
          VAR_FILE: 'environments/{{.ENV}}/debian-variables.pkrvars.hcl'

  build-netboot:
    desc: Build Debian template
    cmds:
      - task: build
        vars:
          TEMPLATE_PREFIX: netboot-vm
          VAR_FILE: 'environments/{{.ENV}}/netboot-variables.pkrvars.hcl'

  clean:
    desc: Clean up Packer artifacts
    dir: '{{.ROOT_DIR}}/packer'
    cmds:
      - rm -f packer.log
      - rm -rf downloaded_iso_path