---
- name: Deploy BookStack
  hosts: app_bookstack
  become: true

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_role:
        name: common

  roles:
    - role: docker_service
      vars:
        service_name: bookstack
        service_compose_template: "{{ playbook_dir }}/templates/compose.yaml.j2"
        service_user: "{{ bookstack_user }}"
        service_group: "{{ bookstack_group }}"
        service_images:
          - "{{ bookstack_image }}"
          - "{{ bookstack_db_image }}"
