---
- name: Deploy Split Horizon DNS Configuration
  hosts: dns_servers
  gather_facts: true
  become: true
  
  tasks:
    - name: Pull latest changes from repository
      become_user: "{{ ansible_user }}"
      ansible.builtin.git:
        repo: "{{ homelab_repo_url }}"
        dest: "{{ homelab_repo_path }}"
        version: "{{ homelab_repo_branch }}"
        force: true
      register: repo_updated
    
    - name: Get DNS server configuration for current host
      ansible.builtin.set_fact:
        current_dns_server: "{{ item }}"
      when: item.ip == ansible_default_ipv4.address
      loop: "{{ dns_servers }}"
    
    - name: Set docker compose command
      ansible.builtin.set_fact:
        docker_compose_cmd: "docker compose"
    
    - name: Restart DNS containers to load new configuration
      ansible.builtin.shell:
        cmd: |
          {{ docker_compose_cmd }} down
          {{ docker_compose_cmd }} up -d
        chdir: "{{ current_dns_server.compose_path }}"
      when: current_dns_server is defined
      register: dns_restarted
    
    - name: Wait for DNS service to be ready
      ansible.builtin.wait_for:
        port: 53
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60
      when: dns_restarted.changed | default(false)
    
    - name: Test split horizon DNS - internal resolution
      ansible.builtin.command:
        cmd: dig @{{ ansible_default_ipv4.address }} nginx.samuelcalvert.com +short
      register: dns_test_split
      changed_when: false
      failed_when: false
    
    - name: Test local domain resolution
      ansible.builtin.command:
        cmd: dig @{{ ansible_default_ipv4.address }} nginx.local.samuelcalvert.com +short
      register: dns_test_local
      changed_when: false
      failed_when: false
    
    - name: Display DNS test results
      ansible.builtin.debug:
        msg:
          - "Split horizon test (nginx.samuelcalvert.com): {{ dns_test_split.stdout | default('No response') }}"
          - "Local domain test (nginx.local.samuelcalvert.com): {{ dns_test_local.stdout | default('No response') }}"
          - "Expected result: 10.2.10.140 for both if Traefik LoadBalancer is running"