#ENC[AES256_GCM,data:Q+M7KuCrCb3hrKvkirnKtl9RrKxVElHNEldxqH/PVYNovGko5DKmkghHs3se6vPLcxxqeK73Jdv+g3+XMChy4ywjeU8VhYdPi3W9,iv:zZJWAfNz6aTUqiS/vrcOBarRXihMrLwha6znmlqMYyk=,tag:HENHwOcih1MI7sxUxsMGGA==,type:comment]
#ENC[AES256_GCM,data:5oOFjt+j2V3mRaH8p0aEaneeyXo6zIxpvdTcKuCsWgqQHHlynrhAHoJWVflegC79jvepJhMIfrgWf72TI7+x4bwV6Pnsq2Xlh70=,iv:TbRsGFHyEKuGrrlCUv8tJAm1IDjGttaEzoAuSGBTV8U=,tag:vU4iL5LnPXhu3J6B4E6H9g==,type:comment]
#ENC[AES256_GCM,data:w0qTbsPP4Yq+0bG8dUnRGbg4qeXVAXVHkp2Rn0AoN1nkX8jIuXpsQrTZx3QTpUZd5uSgxhFWLsb4qWgQ6kvJSkd29X7zHpiZV90=,iv:uE1xcxYflZJTcR5/TV7+DuelzQ0cKQSsF4NqopCsOxc=,tag:482Dixv/EBDy0Z6ctFQQvg==,type:comment]
#ENC[AES256_GCM,data:w5zc46zNyWAAyXM+sQIeYBVj03u9zNZAiBZECymEqB2C9G0iH4qKBH5PjucOtb4rRc8CQgXGKPPBQkgNwl+TqmNjFSP/xa53EFAFIeTI,iv:3GyFJXguX8RJx10sY6dhBNO9DnWDpH/Cf7JpUHq+we0=,tag:RKP8WWvgZefVafIMEuPbSg==,type:comment]
netboot_user_password_hash: ENC[AES256_GCM,data:AAeQodwCdRhpw1DlrX9J9DeLAgYphXlq1V6+04UmvJyvRb7QS31kZ9sLIuT41pnu9SpKMlvIDSwqwa+OUGkUe2xb0RZ/06Nz1qngCP8b+r/cPCduXm5cYilXRx/sffDyndp8iitzX3geag==,iv:LPB7/1RD4baBeYACJixTPDjWNqgxcN8E5fJrzBAopgM=,tag:OHKgmZ3n5L5nov0M2O2buQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTUh2dFEwcGtNemdncCtw
            VXpNSUFXV29QbDNnRndjZHd4QVY5MGkrS0NZClFuQ1pmbFV1OVNrb1pOUnJNM2hn
            ZzJWWGd6K0tKY0xsQ0ZpWmVpbkdXb1UKLS0tIC8yNG1SbHdWWlAwY3JoMkpBalpI
            SjlnQkJQMlJidTREMzZtL056WlRpZzgKbjHtC9mKp7XUdkp9lTRjWPQRMc5tkv+K
            /g0Icb6OZzLkRwOMv9OT+48eqqYqMS860RfaYhBeJTgr3Pe4mQ+e+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
    lastmodified: "2026-08-18T11:04:07Z"
    mac: ENC[AES256_GCM,data:hYvSYu2maiBPpXEK1MnOsEd3zJzuKSypEIJYIhp6Pt1d1H1rYczmxXqEScVApnA7FqYStLxzFYWIcwl+4U1FPKigCfpCiZvxhSEJs/p01fsNy9S06KS3cyLm9ykc9l/qQTtDuFKK4IWtKrdWk9W5TtvAPrWYb/xuntMa99sVNw8=,iv:gry9d5dzrimrTqKs2dn87Of311WyshsGbjObuCipwMs=,tag:+H2824I8eDdpzdwhMXA2dQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
