#ENC[AES256_GCM,data:Q+M7KuCrCb3hrKvkirnKtl9RrKxVElHNEldxqH/PVYNovGko5DKmkghHs3se6vPLcxxqeK73Jdv+g3+XMChy4ywjeU8VhYdPi3W9,iv:zZJWAfNz6aTUqiS/vrcOBarRXihMrLwha6znmlqMYyk=,tag:HENHwOcih1MI7sxUxsMGGA==,type:comment]
#ENC[AES256_GCM,data:5oOFjt+j2V3mRaH8p0aEaneeyXo6zIxpvdTcKuCsWgqQHHlynrhAHoJWVflegC79jvepJhMIfrgWf72TI7+x4bwV6Pnsq2Xlh70=,iv:TbRsGFHyEKuGrrlCUv8tJAm1IDjGttaEzoAuSGBTV8U=,tag:vU4iL5LnPXhu3J6B4E6H9g==,type:comment]
#ENC[AES256_GCM,data:w0qTbsPP4Yq+0bG8dUnRGbg4qeXVAXVHkp2Rn0AoN1nkX8jIuXpsQrTZx3QTpUZd5uSgxhFWLsb4qWgQ6kvJSkd29X7zHpiZV90=,iv:uE1xcxYflZJTcR5/TV7+DuelzQ0cKQSsF4NqopCsOxc=,tag:482Dixv/EBDy0Z6ctFQQvg==,type:comment]
#ENC[AES256_GCM,data:w5zc46zNyWAAyXM+sQIeYBVj03u9zNZAiBZECymEqB2C9G0iH4qKBH5PjucOtb4rRc8CQgXGKPPBQkgNwl+TqmNjFSP/xa53EFAFIeTI,iv:3GyFJXguX8RJx10sY6dhBNO9DnWDpH/Cf7JpUHq+we0=,tag:RKP8WWvgZefVafIMEuPbSg==,type:comment]
netboot_user_password_hash: ENC[AES256_GCM,data:yQX2c96jow+yzkYaaWiMyMHvu9fXb+wD9kn3Nhc2Wky9tTtFKlOhvyxYgL6TXb46dCtLCr1H1lnLrwj7eVj2FjBRkA/Hjt9vZvcUhiCQetmnahsNoq4R7mtHR3W8L1GuXswKauvFoR1Yiw==,iv:CEpANxfMqo9MYHzdQXufWH0WAle7WCCadTgFy8AoH8Q=,tag:33F/8aLISD1M/CftWtVYaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTUh2dFEwcGtNemdncCtw
            VXpNSUFXV29QbDNnRndjZHd4QVY5MGkrS0NZClFuQ1pmbFV1OVNrb1pOUnJNM2hn
            ZzJWWGd6K0tKY0xsQ0ZpWmVpbkdXb1UKLS0tIC8yNG1SbHdWWlAwY3JoMkpBalpI
            SjlnQkJQMlJidTREMzZtL056WlRpZzgKbjHtC9mKp7XUdkp9lTRjWPQRMc5tkv+K
            /g0Icb6OZzLkRwOMv9OT+48eqqYqMS860RfaYhBeJTgr3Pe4mQ+e+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
    lastmodified: "2026-08-20T09:17:00Z"
    mac: ENC[AES256_GCM,data:XjHznF6fRTaQRITQ1XmBXIVa4YXeQWCWJ0Yd2y3LSLyQcgMJ5mhVWowuR8K4OaecZKOQrgXBCBkLF02GImq+Ro0ugFtHRuT97kqmYQLVwlQj0a1hyIEjyEatqyE0uFfdrxJMNmHUnHfxIgR4f6gI1NXWfCx0Z3B88rgsIJonJ0Q=,iv:d0K3ofBPN/hn7FYiXMRJGmqLXsXhTxSWbcniH2mi8Q0=,tag:TByN4qH16GpnbICy9yxLFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
