#ENC[AES256_GCM,data:3DSoyfySBGG5ig==,iv:9GRKaafBBkuV6eJ46xnSzyCtU9M7TJJfw5f/WDf7izo=,tag:3lBssgWvk6dW9FcB/psULg==,type:comment]
tailscale_auth_key: ENC[AES256_GCM,data:+03G4zWrrsa3kRqLX2CGfAMq6YAjeRH53ZNy7hRdCl9NGValA8ejzUhq9FP9mfnH7LfDsoc5sC1N1ZeqEQ==,iv:tmO2a6HS8BmDLOTHZG2CjAnnNm9Pd3QgDmkmuOGd4Ho=,tag:BW6d6toJPvH0R85+XK+Tmg==,type:str]
#ENC[AES256_GCM,data:LuV0/JdLxxk=,iv:mQauJESsKzbIVn5Ca2CiMek3pqpanjTps1dPd7EvINw=,tag:xOgnjYpcgBoGQG3bbG+oAw==,type:comment]
cf_api_token: ENC[AES256_GCM,data:G7VhWuUjRyYCRHsX5RmvjkQ6sYtPLwrxrVoDNKpT1HLKXR3zkzbCSQ==,iv:8UTku8J77F36XSlFvqgtsOI+hHyAtRsIZL9Y8tkz5xI=,tag:BEQwAc665wvgRTNseK9MjA==,type:str]
cf_email: ENC[AES256_GCM,data:bGmoO1gk0wVcLBW0gbNB6zr9OHW7ICFwDGYkVQ==,iv:pdziwqjvUtAjz4fDZFEkMY17vEm6Qn8bKb/FJeIYYvc=,tag:IuA+g9+MJeAWb4lLyScY3A==,type:str]
convertx_jwt_secret: ENC[AES256_GCM,data:o6W9ZTXKAY8na3J9rwXivivVFft18FQ2c6Ld/ME6O0okKxaHqtQZd1WKk1vQTNXvg27Die+VeFLSCCRtxeAm4A==,iv:AHw28kBPd0WveT6cZ4gzIwHQZhJXaRQiM2eBioezlsw=,tag:cLmQgpl8rFQNTweCEsSgUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRDIyMDhmbzhOdnJxZEx5
            eVB2TWNKSTNJb0hnM0VlN2U1N0xUSUszWkhBCkI2TW5OTHV1Z0dOWWRxZDZ0OHNj
            RTdCS1F1ZEZXVURGcDYwbFNwSnBHVzgKLS0tIC96WkNNZEJONXBJWWtJL0t2aERN
            RTJOUFluMnlqYzF1a2dMNnFqekVEMlUKAHTY22xEuyvZ/dkUiYGj6xOjvYoX8IBK
            fxD5xR4NyFmd39Z5vQFSMp4jLt67ZIGrXPQYhnbUFlr/mKYAPiJ8xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
    lastmodified: "2026-08-11T11:05:45Z"
    mac: ENC[AES256_GCM,data:Q5mnkjDVmRE1oXDULgwYOBKeHzE0Wi1kA9YxlAjN1H3gkM96TwmLvSn24np4zH0sot6NB9bbZbDfGG2yvJvAZKfEkIbtyKKQ0wcfBCrgaI3Qlp6WBG0CxJhRYU6AJJN231yGJzKlANb/WpZl6XFT0MTH7YbVe2nT2YzoxuqjWK4=,iv:w0f0MZ4t9icRW4Fpqjc9ALExvlO74/TsGkALgUcK7ts=,tag:CW1RkeycDY7Lu7m8nVjMjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
