# --- Infrastructure ---

[infra_dns]
10.3.0.53

[infra_monitoring]
10.3.0.30

[infra_reverse-proxy]
10.3.0.80

# --- Parent groups ---

[infrastructure:children]
infra_dns
infra_monitoring
infra_reverse-proxy

[services:children]
infra_dns
infra_reverse-proxy
