# --- Infrastructure ---

[infra_networking]
10.3.20.53

[infra_ca]
10.3.20.9

[infra_ntp]
10.3.20.123

[infra_monitoring]
10.3.20.30

# --- Apps ---

[app_homeassistant]
10.3.20.50

# --- Parent groups ---

[infrastructure:children]
infra_networking
infra_ca
infra_ntp
infra_monitoring

[apps:children]
app_homeassistant
