# --- Infrastructure ---

[infra_networking]
10.3.0.53

[infra_ca]
10.3.0.9

[infra_ntp]
10.3.0.123

[infra_monitoring]
10.3.0.30

# --- Apps ---

[app_homeassistant]
10.3.0.50

# --- Parent groups ---

[infrastructure:children]
infra_networking
infra_ca
infra_ntp
infra_monitoring

[applications:children]
app_homeassistant
