---
wil_services:
  # Infrastructure
  - name: vm
    backend_host: 10.2.20.7
    backend_port: 8006
    proxied: true
    tls_skip_verify: true
  - name: nas
    backend_host: 10.2.0.100
    backend_port: 80
    proxied: true
  - name: kvm
    backend_host: 10.2.0.78
    backend_port: 443
    proxied: true
    tls_skip_verify: true

  # Monitoring
  - name: grafana
    backend_host: 10.2.20.30
    backend_port: 3000
    proxied: true
  - name: prometheus
    backend_host: 10.2.20.30
    backend_port: 9090
    proxied: true
  - name: homepage
    backend_host: 10.2.20.30
    backend_port: 3002
    proxied: true

  # Haivision
  - name: hmp
    backend_host: 10.2.20.40
    backend_port: 443
    proxied: false
  - name: hmg
    backend_host: 10.2.20.186
    backend_port: 443
    proxied: false

  # Apps
  - name: convert
    backend_host: 10.2.0.5
    backend_port: 3100
    proxied: true
  - name: tools
    backend_host: 10.2.20.60
    backend_port: 8070
    proxied: true
  - name: bookstack
    backend_host: 10.2.20.60
    backend_port: 8074
    proxied: true
  - name: cyberchef
    backend_host: 10.2.20.60
    backend_port: 8071
    proxied: true
  - name: openbooks
    backend_host: 10.2.20.45
    backend_port: 8072
    proxied: true
  - name: pdf
    backend_host: 10.2.20.60
    backend_port: 8073
    proxied: true
  - name: kasm
    backend_host: 10.2.20.60
    backend_port: 4443
    proxied: true
    tls_skip_verify: true
  - name: files
    backend_host: 10.2.20.70
    backend_port: 8080
    proxied: true
    forward_headers: true
  - name: bin
    backend_host: 10.2.20.70
    backend_port: 8081
    proxied: true
  - name: roms
    backend_host: 10.2.0.5
    backend_port: 8085
    proxied: true
