apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-backup-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.2.10.100
    path: /mnt/NAS-WIL/Media/k3s-backups/sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-backup-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: sonarr-backup-nfs-pv
---
# Use rclone
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-backup
  namespace: media
spec:
  sourcePVC: sonarr-config
  trigger:
    schedule: "0 3 * * *"
  rclone:  # Changed from rsync to rclone
    destinationPVC: sonarr-backup-nfs
    rcloneConfig: |
      # No config needed for local filesystem
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-rbd
    accessModes:
      - ReadWriteOnce
    capacity: 10Gi
    # Optional: Add these for better control
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000