apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-backup-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.2.10.100
    path: /mnt/NAS-WIL/Media/k3s-backups/sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-backup-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: sonarr-backup-nfs-pv
---
# Using rsync which is simpler for PVC to PVC copies
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-backup
  namespace: media
spec:
  sourcePVC: sonarr-config
  trigger:
    schedule: "0 3 * * *"  # Daily at 3 AM
  rsync:
    copyMethod: Snapshot
    storageClassName: ceph-rbd
    volumeSnapshotClassName: csi-ceph-blockpool
    destinationPVC: sonarr-backup-nfs
    # SSH not needed for PVC to PVC copy
    sshKeys: ~
    # Preserve permissions and ownership
    rsyncOpts:
      - "--archive"
      - "--delete"
      - "--hard-links"
      - "--acls"
      - "--xattrs"
    # Set proper permissions for the mover pod
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000