apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-backup-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.2.10.100
    path: /mnt/NAS-WIL/Media/k3s-backups/sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-backup-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: sonarr-backup-nfs-pv
---
# Create secret for restic repository password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-restic-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: sonarr-restic-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        RESTIC_PASSWORD: "{{ .resticPassword | b64enc }}"
  data:
    - secretKey: resticPassword
      remoteRef:
        key: sonarr-backup
        property: restic-password
---
# Restic-based backup - works great for PVC-to-PVC without SSH
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-backup
  namespace: media
spec:
  sourcePVC: sonarr-config
  trigger:
    schedule: "0 3 * * *"  # Daily at 3 AM
  restic:
    # Restic will create a repository on the destination PVC
    repository: sonarr-backup-nfs
    copyMethod: Snapshot
    storageClassName: ceph-rbd
    volumeSnapshotClassName: csi-ceph-blockpool
    # Reference the secret containing RESTIC_PASSWORD
    repositorySecretRef:
      name: sonarr-restic-secret
    # Retain 7 daily backups
    retain:
      daily: 7
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000