apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: dev
  CLUSTER_DOMAIN: dev.home.local
  CLUSTER_REGION: homelab
  # Storage
  STORAGE_CLASS: ceph-rbd
  VOLSYNC_ENABLED: "false"
  # Ceph Configuration
  CEPH_CLUSTER_ID: "de931674-fd79-4563-b46c-6581a5a7a418"
  CEPH_MON1_IP: "10.0.0.1"
  CEPH_MON2_IP: "10.0.0.2"
  CEPH_MON3_IP: "10.0.0.3"
  CEPH_POOL_NAME: "kubernetes"
  # Networking
  INGRESS_TYPE: nodeport
  LOAD_BALANCER_IP_RANGE: 192.168.1.220-192.168.1.230
  # Resources - smaller for dev
  DEFAULT_CPU_REQUEST: 10m
  DEFAULT_MEMORY_REQUEST: 64Mi