apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: dev
  CLUSTER_DOMAIN: dev.home.local
  CLUSTER_REGION: homelab
  # Storage
  STORAGE_CLASS: ceph-rbd
  VOLSYNC_ENABLED: "false"
  # Ceph Configuration
  CEPH_CLUSTER_ID: "0f72fe9d-dd7f-49c1-b7a8-86aabb02459f"
  CEPH_MON1_IP: "10.0.0.81"
  CEPH_MON2_IP: "10.0.0.82"
  CEPH_MON3_IP: "10.0.0.83"
  CEPH_POOL_NAME: "kubernetes"
  # Networking
  INGRESS_TYPE: nodeport
  LOAD_BALANCER_IP_RANGE: 192.168.1.220-192.168.1.230
  # Resources - smaller for dev
  DEFAULT_CPU_REQUEST: 10m
  DEFAULT_MEMORY_REQUEST: 64Mi

  ONEPASSWORD_CONNECT_HOST: "http://10.1.20.5:7070"
  ONEPASSWORD_VAULT: "k3s-dev"