# ansible/roles/dns/primary/tasks/main.yml
---
- name: Create DNS config directory
  ansible.builtin.file:
    path: /opt/dns/config
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../../docker/bind9/docker-compose.yaml"
    dest: /opt/dns/docker-compose.yaml
    mode: '0644'

- name: Copy DNS configuration files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../../docker/bind9/config/{{ item }}"
    dest: "/opt/dns/config/{{ item }}"
    mode: '0644'
  loop:
    - named.conf
    - home-samuel-computer.zone
    - 0.1.10.in-addr.arpa.zone

- name: Deploy and restart primary DNS container
  community.docker.docker_compose:
    project_src: /opt/dns
    pull: yes
    recreate: always