apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: '>=1.4.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    longhornUI:
      replicas: 1
