# --- Infrastructure ---

[infra_networking]
10.2.20.53

[infra_ca]
10.2.20.9

[infra_ntp]
10.2.20.123

[infra_monitoring]
10.2.20.30

# --- Apps ---

[app_mediastack]
10.2.0.5

[app_gamesserver]
10.2.20.50

[app_website]
10.2.20.45

[app_birdle]
10.2.20.45

[app_convertx]
10.2.0.5

[app_restreamer]
10.2.0.5

[app_ittools]
10.2.20.60

[app_bookstack]
10.2.20.60

[app_cyberchef]
10.2.20.60

[app_openbooks]
10.2.20.45

[app_stirlingpdf]
10.2.20.60

[app_kasm]
10.2.20.60

[app_seafile]
10.2.20.70

[app_microbin]
10.2.20.70

[app_romm]
10.2.0.5

[app_frigate]
10.2.0.5

# --- Parent groups ---

[infrastructure:children]
infra_networking
infra_ca
infra_ntp
infra_monitoring

[apps:children]
app_mediastack
app_gamesserver
app_website
app_birdle
app_convertx
app_restreamer
app_ittools
app_bookstack
app_cyberchef
app_openbooks
app_stirlingpdf
app_kasm
app_seafile
app_microbin
app_romm
app_frigate
