# --- Infrastructure ---

[infra_networking]
10.2.20.53

[infra_ca]
10.2.20.9

[infra_ntp]
10.2.20.123

[infra_monitoring]
10.2.20.30

# --- Apps ---

[app_mediastack]
10.2.0.5

[app_gamesserver]
10.2.20.50

[app_website]
10.2.20.45

[app_birdle]
10.2.20.45

[app_restreamer]
10.2.0.5

[app_openbooks]
10.2.20.45

[app_kasm]
10.2.20.60

[app_seafile]
10.2.20.70

[app_frigate]
10.2.0.5

[app_subsearch]
10.2.0.5

[app_cloud_gaming]
10.2.20.80

[app_work]
10.2.20.60

# --- Parent groups ---

[infrastructure:children]
infra_networking
infra_ca
infra_ntp
infra_monitoring

[apps:children]
app_mediastack
app_gamesserver
app_website
app_birdle
app_restreamer
app_openbooks
app_kasm
app_seafile
app_frigate
app_subsearch
app_cloud_gaming
app_work
