---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Ansible & YAML
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install yamllint ansible-core ansible-lint

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install community.sops
          ansible-galaxy collection install ansible.posix

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: |
          cd ansible
          ansible-lint

  syntax-check:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install ansible-core

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install community.sops
          ansible-galaxy collection install ansible.posix

      - name: Check playbook syntax
        run: |
          cd ansible
          ansible-playbook --syntax-check playbooks/dns/deploy.yml
          ansible-playbook --syntax-check playbooks/time/deploy.yml
          ansible-playbook --syntax-check playbooks/media/deploy.yml